### ISSUE TITLE
Renaming monster stat categories?

### ISSUE THREAD

**Issue by brownem** [Krozark/RPG-LaTeX-Template#4]
I've been playing around with it a bit, but haven't had much luck cracking it - but how can I rename the STR, DEX, CON, INT, WIS, CHA in the rpg-monsterbox? Or am I underestimating the difficulty of this change?

**Comment by ryumaou** [comment]
> 
> 
> I've been playing around with it a bit, but haven't had much luck cracking it - but how can I rename the STR, DEX, CON, INT, WIS, CHA in the rpg-monsterbox? Or am I underestimating the difficulty of this change?

Check the \lib\book\rpg-monster.sty file at line 150  All the stats look like they're defined there.

**Comment by brownem** [comment]
I changed the names on both lines 151-156, as well as the ones on 164. No change to the render. I think there is something else going on that I am not seeing.

**Comment by ryumaou** [comment]
> 
> 
> I changed the names on both lines 151-156, as well as the ones on 164. No change to the render. I think there is something else going on that I am not seeing.

Hmm, I see some definitions in rpg-strings.sty and rpg-strings-captions.sty that may be what's controlling it.  Also check captions-template.txt to see if the information there points you in a good direction.  Seems like this particular section was in development and sort of got left part way through some changes, which may also be the problem.

**Comment by brownem** [comment]
The rpg-strings.sty did the trick. Missed it the first go through, thanks. I am not sure if rpg-strings-captions.sty is needed for anything other than translations, but I did not need to modify it to finally get the new names to take.
